apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "agent.fullname" . }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "agent.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ template "agent.serviceAccount" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      - name: sampler-volume
        emptyDir: {}
      - name: sampler-pkg-volume
        emptyDir: {}
      - name: metric-sampler-volume
        emptyDir: {}
      - name: metric-sampler-pkg-volume
        emptyDir: {}
      - name: log-sampler-volume
        emptyDir: {}
      - name: log-sampler-pkg-volume
        emptyDir: {}
      - name: host-proc-path
        hostPath:
          path: /proc
      - name: default-netns-path
        hostPath:
          path: /var/run/netns
      - name: docker-netns-path
        hostPath:
          path: /var/run/docker/netns
      - name: config
        configMap:
          name: {{ template "agent.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "agent.image" . }}
          imagePullPolicy: {{ include "agent.imagePullPolicy" . }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            capabilities:
              add:
              - SYS_PTRACE
              - SYS_ADMIN
            privileged: true
          env:
            - name: S6_KEEP_ENV
              value: "1"
            - name: AGENT_KEY
              value: {{ .Values.AGENT_KEY }}
            - name: SERVER_ADDR
              value: {{ .Values.SERVER_ADDR }}
            - name: PROXY_ADDR
              value: {{ .Values.PROXY_ADDR }}
            - name: HOST_FS
              value: "/rootfs"
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: SCAN_NAMESPACES
              value: {{ .Values.SCAN_NAMESPACES }}
            - name: SCAN_RESOURCE_TYPES
              value: {{ .Values.SCAN_RESOURCE_TYPES }}
            - name: SPECIFIED_CLUSTER_ID
              value: {{ .Values.SPECIFIED_CLUSTER_ID | quote }}
            - name: CUSTOM_IP_KEY
              value: {{ .Values.CUSTOM_IP_KEY }}
            - name: COLLECTION_SPECIAL_ATTRIBUTES
              value: {{ .Values.COLLECTION_SPECIAL_ATTRIBUTES }}
            - name: NAMESPACE_LABEL_SELECTOR
              value: {{ .Values.NAMESPACE_LABEL_SELECTOR }}
            - name: SCHEMA
              value: {{ .Values.SCHEMA}}
          volumeMounts:
            - name: sampler-volume
              mountPath: /usr/local/easyops/easy_process_sampler
              subPath: easy_process_sampler
            - name: sampler-pkg-volume
              mountPath: /usr/local/easyops/pkg/conf/process_sampler_linux
              subPath: process_sampler_linux
            - name: metric-sampler-volume
              mountPath: /usr/local/easyops/easy_metric_sampler
              subPath: easy_metric_sampler
            - name: metric-sampler-pkg-volume
              mountPath: /usr/local/easyops/pkg/conf/metric_sampler_linux
              subPath: metric_sampler_linux
            - name: log-sampler-volume
              mountPath: /usr/local/easyops/easy_log_sampler
              subPath: easy_log_sampler
            - name: log-sampler-pkg-volume
              mountPath: /usr/local/easyops/pkg/conf/log_sampler_linux
              subPath: log_sampler_linux
            - name: host-proc-path
              mountPath: /rootfs/proc
            - name: default-netns-path
              mountPath: /rootfs/var/run/netns
            - name: docker-netns-path
              mountPath: /rootfs/var/run/docker/netns
            - mountPath: /usr/local/easyops/agent/conf/easy_monitor.yaml
              name: config
              subPath: easy_monitor.yaml
              readOnly: true
      initContainers:
        - name: process-sampler-init
          image: {{ include "process-sampler.image" . }}
          command: ['sh', '-c', 'mv /usr/local/easyops/easy_process_sampler /sampler-pkg && mv /sampler/process_sampler_linux /pkg-conf']
          volumeMounts:
            - name: sampler-volume
              mountPath: /sampler-pkg
            - name: sampler-pkg-volume
              mountPath: /pkg-conf
        - name: metric-sampler-init
          image: {{ include "metric-sampler.image" . }}
          command: ['sh', '-c', 'mv /usr/local/easyops/easy_metric_sampler /sampler-pkg && mv /sampler/metric_sampler_linux /pkg-conf']
          volumeMounts:
            - name: metric-sampler-volume
              mountPath: /sampler-pkg
            - name: metric-sampler-pkg-volume
              mountPath: /pkg-conf
        - name: log-sampler-init
          image: {{ include "log-sampler.image" . }}
          command: [ 'sh', '-c', 'mv /usr/local/easyops/easy_log_sampler /sampler-pkg && mv /sampler/log_sampler_linux /pkg-conf' ]
          volumeMounts:
            - name: log-sampler-volume
              mountPath: /sampler-pkg
            - name: log-sampler-pkg-volume
              mountPath: /pkg-conf
      {{- include "networkAndPid" . | nindent 6 }}
      terminationGracePeriodSeconds: 10
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
