apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "agent.fullname" . }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "agent.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ template "agent.serviceAccount" . }}
      hostNetwork: false
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      - name: sampler-volume
        emptyDir: {}
      - name: sampler-pkg-volume
        emptyDir: {}
      - name: host-proc-path
        hostPath:
          path: /proc
      - name: default-netns-path
        hostPath:
          path: /var/run/netns
      - name: docker-netns-path
        hostPath:
          path: /var/run/docker/netns
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            capabilities:
              add:
              - SYS_PTRACE
              - SYS_ADMIN
            privileged: true
          env:
            - name: S6_KEEP_ENV
              value: "1"
            - name: AGENT_KEY
              value: {{ .Values.AGENT_KEY }}
            - name: SERVER_ADDR
              value: {{ .Values.SERVER_ADDR }}
            - name: HOST_FS
              value: "/rootfs"
          volumeMounts:
            - name: sampler-volume
              mountPath: /usr/local/easyops/easy_process_sampler
              subPath: easy_process_sampler
            - name: sampler-pkg-volume
              mountPath: /usr/local/easyops/pkg/conf/process_sampler_linux
              subPath: process_sampler_linux
            - name: host-proc-path
              mountPath: /rootfs/proc
            - name: default-netns-path
              mountPath: /rootfs/var/run/netns
            - name: docker-netns-path
              mountPath: /rootfs/var/run/docker/netns

{{- if .Values.initContainers }}
      initContainers:
{{- range $key, $value := .Values.initContainers }}
      - name: "{{ $key }}"
{{ toYaml $value | indent 8 }}
{{- end }}
{{- end }}
      hostPID: false
      hostNetwork: false
      terminationGracePeriodSeconds: 10
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
