apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "agent.fullname" . }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
data:
  easy_monitor.yaml: |-
    easy_agent:
        name: "easy_monitor"
        unix_listen:
            proto: unix
            addr: unix:///usr/local/easyops/agent/plugin.sock
    resource_usage:
        samplers: []
