# Default values for agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.cn-hangzhou.aliyuncs.com/easyops/agent
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "3.37.11"

resources:
  limits:
    cpu: 1000m
    memory: 2048Mi
  requests:
    cpu: 500m
    memory: 1024Mi

managedServiceAccount: true

clusterRoleRules:
  - apiGroups: [""]
    resources:
      - nodes
      - namespaces
      - events
      - pods
      - services
      - endpoints
      - configmaps
      - persistentvolumeclaims
      - persistentvolumes
      - resourcequotas
      - secrets
      - limitranges
      - serviceaccounts
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "apps" ]
    resources:
      - statefulsets
      - daemonsets
      - deployments
      - replicasets
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "batch" ]
    resources:
      - cronjobs
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "networking.k8s.io" ]
    resources:
      - ingresses
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "storage.k8s.io" ]
    resources:
      - storageclasses
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "autoscaling" ]
    resources:
      - horizontalpodautoscalers
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "rbac.authorization.k8s.io" ]
    resources:
      - roles
      - rolebindings
      - clusterroles
      - clusterrolebindings
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "apiextensions.k8s.io" ]
    resources:
      - customresourcedefinitions
    verbs: [ "get", "list", "watch" ]
  - apiGroups:
    - ""
    resources:
    - nodes/stats
    verbs:
    - get
  - nonResourceURLs:
    - "/metrics"
    verbs:
    - get

serviceAccount: ""

configmap: "agent-config"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# sampler
initContainers:
  process-sampler-init:
    image: "registry.cn-hangzhou.aliyuncs.com/easyops/easy-process-sampler:1.17.18"
    command: ['sh', '-c', 'mv /usr/local/easyops/easy_process_sampler /sampler-pkg && mv /sampler/process_sampler_linux /pkg-conf']
    volumeMounts:
      - name: sampler-volume
        mountPath: /sampler-pkg
      - name: sampler-pkg-volume
        mountPath: /pkg-conf
  metric-sampler-init:
    image: "registry.cn-hangzhou.aliyuncs.com/easyops/easy-metric-sampler:1.7.25"
    command: ['sh', '-c', 'mv /usr/local/easyops/easy_metric_sampler /sampler-pkg && mv /sampler/metric_sampler_linux /pkg-conf']
    volumeMounts:
      - name: metric-sampler-volume
        mountPath: /sampler-pkg
      - name: metric-sampler-pkg-volume
        mountPath: /pkg-conf
