# Default values for agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.cn-hangzhou.aliyuncs.com/easyops/agent
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "3.33.2"

resources:
  limits:
    cpu: 1000m
    memory: 4096Mi
  requests:
    cpu: 500m
    memory: 2048Mi

managedServiceAccount: true

clusterRoleRules:
  - apiGroups: [""]
    resources:
      - nodes
      - namespaces
      - events
      - pods
      - services
      - endpoints
      - configmaps
      - persistentvolumeclaims
      - persistentvolumes
      - resourcequotas
      - secrets
      - deployments
      - daemonsets
      - ingresses
    verbs: ["get", "list", "watch"]
  - apiGroups: ["extensions"]
    resources:
      - replicasets
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources:
      - statefulsets
      - deployments
      - replicasets
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources:
      - nodes/stats
    verbs: ["get"]
  - apiGroups:
    - ""
    resources:
    - nodes/stats
    verbs:
    - get
  - nonResourceURLs:
    - "/metrics"
    verbs:
    - get

serviceAccount: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# sampler
initContainers:
  process-sampler-init:
    image: "registry.cn-hangzhou.aliyuncs.com/easyops/easy-process-sampler:1.13.3"
    command: ['sh', '-c', 'mv /usr/local/easyops/easy_process_sampler /sampler-pkg && mv /sampler/process_sampler_linux /pkg-conf']
    volumeMounts:
      - name: sampler-volume
        mountPath: /sampler-pkg
      - name: sampler-pkg-volume
        mountPath: /pkg-conf
