# Default values for agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

agent:
  image:
    repository: registry.cn-hangzhou.aliyuncs.com/easyops/agent
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: 3.37.12
  process_sampler:
    repository: registry.cn-hangzhou.aliyuncs.com/easyops/easy-process-sampler
    tag: 1.39.15
  metric_sampler:
    repository: registry.cn-hangzhou.aliyuncs.com/easyops/easy-metric-sampler
    tag: 1.16.3

ebpf_agent:
  image:
    repository: registry.cn-hangzhou.aliyuncs.com/easyops/agent-ebpf
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: 3.45.33
  process_sampler:
    repository: registry.cn-hangzhou.aliyuncs.com/easyops/easy-ebpf-process-sampler
    tag: 1.39.11
  metric_sampler:
    repository: registry.cn-hangzhou.aliyuncs.com/easyops/easy-metric-sampler
    tag: 1.16.3

resources:
  limits:
    cpu: 1000m
    memory: 3072Mi
  requests:
    cpu: 500m
    memory: 1024Mi

managedServiceAccount: true

clusterRoleRules:
  - apiGroups: [""]
    resources:
      - nodes
      - namespaces
      - events
      - pods
      - services
      - endpoints
      - configmaps
      - persistentvolumeclaims
      - persistentvolumes
      - resourcequotas
      - secrets
      - limitranges
      - serviceaccounts
    verbs: [ "get", "list", "watch" ]
#Used for leadership node elections
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - create
      - update
  - apiGroups: [ "apps" ]
    resources:
      - statefulsets
      - daemonsets
      - deployments
      - replicasets
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "batch" ]
    resources:
      - jobs
      - cronjobs
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "networking.k8s.io" ]
    resources:
      - ingresses
      - ingressclasses
      - networkpolicies
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "storage.k8s.io" ]
    resources:
      - storageclasses
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "autoscaling" ]
    resources:
      - horizontalpodautoscalers
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "rbac.authorization.k8s.io" ]
    resources:
      - roles
      - rolebindings
      - clusterroles
      - clusterrolebindings
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "apiextensions.k8s.io" ]
    resources:
      - customresourcedefinitions
    verbs: [ "get", "list", "watch" ]
  - apiGroups:
    - ""
    resources:
    - nodes/stats
    verbs:
    - get
  - nonResourceURLs:
    - "/metrics"
    verbs:
    - get

serviceAccount: ""

configmap: "agent-config"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
